server:
  port: 8089
spring:
  rabbitmq:
    host: 192.168.92.131
    port: 5672
    virtual-host: /
    username: itcast
    password: 123321
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hmall?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: searchservice
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.itcast.hotel.pojo